_wandb:
    value:
        cli_version: 0.21.0
        e:
            38ojfjjd46pqcttzi85h9b2tuokubccv:
                args:
                    - C:\Users\Trabajo\Desktop\Endo-SfM-Learner-master\EndoSfMLearner\data\endovis_data
                    - --name
                    - prueba
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "1023121813504"
                        used: "366519042048"
                email: 0228053@up.edu.mx
                executable: C:\Users\Trabajo\.conda\envs\endo_sfmlearner_env\python.exe
                gpu: NVIDIA GeForce RTX 3050 Ti Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2560
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Ti Laptop GPU
                      uuid: GPU-fceba30d-841d-f6dd-51bb-f6fdcdb9e823
                host: Consuk
                memory:
                    total: "16312721408"
                os: Windows-10-10.0.26100-SP0
                program: train.py
                python: CPython 3.8.20
                root: C:\Users\Trabajo\Desktop\Endo-SfM-Learner-master\EndoSfMLearner
                startedAt: "2025-07-07T00:28:40.734141Z"
                writerId: 38ojfjjd46pqcttzi85h9b2tuokubccv
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 41
                - 51
            "2":
                - 1
                - 41
                - 51
            "4": 3.8.20
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
